[package]
name = "printhor-hwi_native"
version = "0.0.4"
edition = "2021"
authors = ["Carlos Barrales Ruiz <cbruiz@gmail.com>"]
description = "Printhor Hardware Abstraction native std for debugging/playgrounding/analysis"
readme = "README.md"
repository = "https://github.com/cbruiz/printhor"
keywords = ["hardware", "abstration", "library", "printhor"]
license = "MIT"
documentation = "https://docs.rs/printhor-hwi_native"
homepage = "https://github.com/cbruiz/printhor"

[lib]

[features]
default = []
# Hardware device features
with-defmt = [] # Just ignore
with-log = ["printhor-hwa-common/with-log", "env_logger"]
with-serial-usb = []
with-serial-port-1 = ["async-std"]
with-serial-port-2 = []
with-serial-port-usb = []
with-print-job = []
with-hot-end = ["embedded-hal", "printhor-hwa-common/with-hot-end"]
with-hot-bed = ["embedded-hal", "printhor-hwa-common/with-hot-bed"]
with-motion = ["printhor-hwa-common/with-motion"]
with-probe = ["embedded-hal"]
with-endstops = []
with-sd-card = ["embedded-sdmmc"]
with-fan-layer = ["embedded-hal"]
with-fan-extra-1 = ["embedded-hal"]
with-laser = ["embedded-hal"]
with-trinamic = ["tmc2209"]
with-ps-on = []
with-spi = []

with-display = []

with-x-axis = []
with-y-axis = []
with-z-axis = []
with-e-axis = []

nightly = ["embassy-executor/nightly"]
executor-interrupt = []
verbose-timings = []
sd-card-uses-spi = []
without-vref-int = []

[dependencies]

embassy-executor = { version = "0.6", default-features = false, features = ["arch-std", "executor-thread", "task-arena-size-16384"] }
embassy-sync = { version = "0.6", features = ["std"] }
embassy-time = { version = "0.3", features = ["std", "generic-queue-128"] }
embassy-futures = { version = "0.1", features = [] }
embassy-embedded-hal = { version = "0.2", features = [] }

embedded-io-async = { version = "0.6.0", optional = true }
embedded-io = { version = "0.6.1", optional = true }

async-std = { version = "1.12.0", optional = true}
gnuplot = {version = "0.0", default-features = false, features=[], optional = true}
env_logger = { version = "0.11", optional = true }
printhor-hwa-common = { version = "0.0", default-features = false, features = ["std"], path = "../../printhor-hwa-common"}
printhor-hwa-utils = { version = "0.0", default-features = false, features = ["std"], path = "../../printhor-hwa-utils"}
async-gcode = {version = "0", default-features = false, features=["parse-trailing-comment", "optional-value", "string-value", "std"] }
embedded-hal = { version = "1.0", default-features = false, optional = true }
embedded-hal-02 = { package = "embedded-hal", version = "0.2", features = ["unproven" ] }
futures = { version = "0.3", default-features = false, features = [] }
embedded-sdmmc = { version = "0.8", default-features = false, optional = true }

lvgl = { version="0", default-features = false, features =[], optional = true }
nb = {version = "1.1", default-features = false, features = []}
tmc2209 = { version = "0.2", optional = true }
thread-priority = { version = "0.15"}

cfg-if = {version = "1.0"}
const_env = { version = "0.1" }

[patch.crates-io]
printhor-hwa-common = { path = "../../printhor-hwa-common" }
printhor-hwa-utils = { path = "../../printhor-hwa-utils" }
embassy-executor = { path = "../../libs/embassy" }
embassy-sync = { path = "../../libs/embassy" }
embassy-time = { path = "../../libs/embassy" }
embassy-futures = { path = "../../libs/embassy" }
embassy-embedded-hal = { path = "../../libs/embassy" }
async-gcode = { path = "../../libs/async-gcode" }
