[package]
name = "printhor-hwa-common"
version = "0.0.4"
edition = "2021"
authors = ["Carlos Barrales Ruiz <cbruiz@gmail.com>"]
description = "Printor harware abstraction utillery"
readme = "README.md"
repository = "https://github.com/cbruiz/printhor"
keywords = ["hardware", "abstration", "library", "printhor"]
categories = ["hardware-support"]
license = "MIT"
documentation = "https://docs.rs/printhor-hwa_common"
homepage = "https://github.com/cbruiz/printhor"

[lib]

[features]
std = ["futures-test/std"]
default = [
    "std", "embassy-time/std", "embassy-time/generic-queue-128",
    "with-log",
    "with-serial-usb", "with-serial-port-1", "with-serial-port-2",
    "with-motion", "with-x-axis", "with-y-axis", "with-z-axis", "with-e-axis",
    "with-hot-end", "with-hot-bed"
]
nightly = []
executor-interrupt = []
with-log = ["log", "printhor-hwa-utils/with-log"]
with-defmt = ["defmt", "printhor-hwa-utils/with-defmt"]
with-serial-usb = []
with-serial-port-1 = []
with-serial-port-2 = []
with-ps-on = []
with-probe = []
with-laser = []
with-fan-layer = []
with-fan-extra-1 = []
with-motion = []
with-hot-end = []
with-hot-bed = []

with-x-axis = []
with-y-axis = []
with-z-axis = []
with-e-axis = []

[dependencies]
printhor-hwa-common-macros = { version = "0", path = "../printhor-hwa-common-macros" }
printhor-hwa-utils = { version = "0",  path = "../printhor-hwa-utils", default-features = false, features = [] }
const_env = { version = "0.1.2"}

embassy-sync = { version = "0.6", features = [] }
embassy-executor = { version = "0.6", features = [] }
embassy-time = { version = "0.3", features = [] }

embedded-hal-01 = { package = "embedded-hal", version = "1.0", default-features = false }
embedded-hal-02 = { package = "embedded-hal", version = "0.2", features = ["unproven"] }
embedded-io-async = { version = "0.6", default-features = false, features = [] }
async-gcode = { version = "0.3", default-features = false, features = []}

bitflags = { version = "2.6", default-features = false, features = ["bytemuck"] }
cfg-if = { version = "1.0" }
defmt = {version = "0.3", default-features = false, optional = true}
log = { version = "0.4", default-features = false, optional = true }
strum = { version = "0.26", default-features = false, features = ["derive"] }

[dev-dependencies]
futures-test = { version = "0.3", default-features = false}
tmc2209 = { version = "0.2"}

[patch.crates-io]
embassy-sync = { path = "../libs/embassy/embassy-sync" }
embassy-time = { path = "../libs/embassy/embassy-time" }
async-gcode = { path = "../libs/async-gcode" }